FROM golang:1.18

ENV GOPROXY direct
# install protoc
WORKDIR /protoc
RUN apt update && apt-get install -y unzip
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.1/protoc-3.20.1-linux-x86_64.zip && \
    unzip protoc-3.20.1-linux-x86_64.zip && \
    ln -s /protoc/bin/protoc /bin/protoc
RUN go install github.com/golang/protobuf/protoc-gen-go@latest

WORKDIR /go-grpc
COPY . /go-grpc
RUN go mod download
RUN ./protoc.sh
RUN openssl req -x509 -nodes -newkey rsa:2048 -days 3650 -keyout cert/server-key.pem -out cert/server-cert.pem -subj "/CN=localhost"

CMD /bin/bash
